[Writable]
    LogLevel = 'DEBUG'
[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 8080
ServerBindAddr = ''  # blank value defaults to Service.Host value
StartupMsg = 'device rest started'
# MaxRequestSize limit the request body size in byte of put command
MaxRequestSize = 0 # value 0 unlimit the request size.
RequestTimeout = '5s'

[KongURL]
Server = "127.0.0.1"
AdminPort = 8001
AdminPortSSL = 8444
ApplicationPort = 8000
ApplicationPortSSL = 8443
StatusPort = 8001

[Swagger]
SwaggerPathPrefix="/edgex-swagger-ui/"
SwaggerFileDir="swagger-ui"
CoreDir="openapi/core/v2"
DeviceSdkDir="openapi/device-sdk/v2"
ReverseProxy = true
ProxyPrefix= "proxy"

[[Swagger.CoreComponents]]
Scheme=""
Enable=true
Route="core-command"
ApiVer="/api/v2"
Name="core-command"
FileName="core-command.yaml"
Port="59882"
Host="core-command"
[[Swagger.CoreComponents]]
Enable=true
Route="core-metadata"
ApiVer="/api/v2"
Name="core-metadata"
FileName="core-metadata.yaml"
Port="59881"
Host="edgex-core-metadata"
[[Swagger.CoreComponents]]
Enable=true
Route="core-data"
ApiVer="/api/v2"
Name="core-data"
FileName="core-data.yaml"
Port="59880"
Host="core-data"
[[Swagger.CoreComponents]]
Enable=true
Route="support-notifications"
ApiVer="/api/v2"
Name="support-notifications"
FileName="support-notifications.yaml"
Port="59860"
Host="support-notifications"
[[Swagger.CoreComponents]]
Enable=true
Route="sys-mgmt-agent"
ApiVer="/api/v2"
Name="sys-mgmt-agent"
FileName="support-scheduler.yaml"
Port="58890"
Host="sys-mgmt-agent"
[[Swagger.CoreComponents]]
Enable=true
Route="support-scheduler"
ApiVer="/api/v2"
Name="support-scheduler"
FileName="support-scheduler.yaml"
Port="59861"
Host="support-scheduler"
[[Swagger.DeviceComponents]]
Enable=true
Route="device-virtual"
ApiVer="/api/v2"
FileName="device-sdk.yaml"
Name="device-virtual"
Port="10.0.197.57"
Host="59900"
[[Swagger.DeviceComponents]]
Enable=true
Route="device-rest"
FileName="device-sdk.yaml"
ApiVer="/api/v2"
Name="device-rest"
Port=""
Host=""
